### ISSUE TITLE
Getting errors when debugging with VS Code Server

### ISSUE THREAD

**Issue by stripu** [sabatex/NetDaemonApps.InverterAnenji-4kw-7.2kw#1]
I'm trying to get your app running in Studio Code Server, on my HA instance, and i get the following errors when debugging:

`[19:08:53 INF] NetDaemon.Runtime.Internal.NetDaemonRuntime: Successfully connected to Home Assistant
[19:08:53 INF] NetDaemon.HassModel.Internal.RegistryCache: Initializing RegistryCache
[19:08:53 DBG] NetDaemon.Runtime.Internal.NetDaemonRuntime: Loading applications from folder /config/NetDaemonApps/apps
[19:08:54 ERR] NetDaemon.AppModel.Internal.Application: Error loading app InverterAnenji.Anenji4000App
System.InvalidOperationException: Unable to resolve service for type 'NetDaemon.Extensions.MqttEntityManager.IMqttEntityManager' while attempting to activate 'InverterAnenji.Anenji4000App'.
   at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.ConstructorMatcher.CreateInstance(IServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.CreateInstance(IServiceProvider provider, Type instanceType, Object[] parameters)
   at NetDaemon.AppModel.Internal.AppFactories.FuncAppFactory.<>c__DisplayClass13_0.<CreateFactoryFunc>b__0(IServiceProvider provider)
   at NetDaemon.AppModel.Internal.AppFactories.FuncAppFactory.Create(IServiceProvider provider)
   at NetDaemon.AppModel.Internal.ApplicationContext..ctor(IServiceProvider serviceProvider, IAppFactory appFactory)
   at NetDaemon.AppModel.Internal.Application.InstanceApplication()
[19:08:54 INF] NetDaemon.AppModel.Internal.AppModelContext: Finished loading applications: Enabled 0, Disabled 0, Running 0, Error 1`

I haven't got any experience with NetDaemon, so i have no clue what i'm doing wrong :) 
Tried runngin "dotnet add package NetDaemon.Extensions.Mqtt" from the Studio Code Server terminal, it shows that it's installed, i can see the dll files in the bin/Debug/net8.0 folder, but i still get those errors.
Any clue to what can be the issue?

Thanks for your effort in getting this app running :)

**Comment by stripu** [comment]
Just to make sure there's nothing wrong with Studio Code Server, i tried running the same debug on my local pc, and i get the same type of mesages:

`[21:00:36 INF] NetDaemon.Runtime.Internal.NetDaemonRuntime: Successfully connected to Home Assistant
[21:00:36 INF] NetDaemon.HassModel.Internal.RegistryCache: Initializing RegistryCache
[21:00:36 DBG] NetDaemon.Runtime.Internal.NetDaemonRuntime: Loading applications from folder D:\NetDaemonApps\apps
[21:00:36 ERR] NetDaemon.AppModel.Internal.Application: Error loading app InverterAnenji.Anenji4000App
System.InvalidOperationException: Unable to resolve service for type 'NetDaemon.Extensions.MqttEntityManager.IMqttEntityManager' while attempting to activate 'InverterAnenji.Anenji4000App'.
   at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.ConstructorMatcher.CreateInstance(IServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.CreateInstance(IServiceProvider provider, Type instanceType, Object[] parameters)
   at NetDaemon.AppModel.Internal.AppFactories.FuncAppFactory.<>c__DisplayClass13_0.<CreateFactoryFunc>b__0(IServiceProvider provider)
   at NetDaemon.AppModel.Internal.AppFactories.FuncAppFactory.Create(IServiceProvider provider)
   at NetDaemon.AppModel.Internal.ApplicationContext..ctor(IServiceProvider serviceProvider, IAppFactory appFactory)
   at NetDaemon.AppModel.Internal.Application.InstanceApplication()
[21:00:36 INF] NetDaemon.AppModel.Internal.AppModelContext: Finished loading applications: Enabled 0, Disabled 0, Running 0, Error 1`

I got NetDaemon.Extensions.Mqtt installed properly, or so i think. So what could be the problem?

Thanks

**Comment by stripu** [comment]
Finally managed to get it built, as I had to manually add some lines to program.cs

try
{
    await Host.CreateDefaultBuilder(args)
        .UseNetDaemonAppSettings()
        .UseNetDaemonDefaultLogging()
        .UseNetDaemonRuntime()
        .UseNetDaemonTextToSpeech()
        .UseNetDaemonMqttEntityManagement()   // <--- more specifically, this line
        .ConfigureServices((_, services) =>
            services
                .AddAppsFromAssembly(Assembly.GetExecutingAssembly())
                .AddNetDaemonStateManager()
                .AddNetDaemonScheduler()
                // Add next line if using code generator
                // .AddHomeAssistantGenerated()
        )
        .Build()
        .RunAsync()
        .ConfigureAwait(false);
}

and to appsettings.json i had to append the mqtt config:

"Mqtt": {
    "Host": "192.168.1.200",
    "UserName": "***",
    "Password": "***"`}

now the app is running on HA, but i get these errors:

[21:58:56] INFO: Starting NetDaemon V4 pre-built Runtime using assembly /config/netdaemon4/bin/Debug/net8.0/NetDaemonApps.dll...
[21:58:56 INF] NetDaemon.Runtime.Internal.NetDaemonRuntime: Starting NetDaemon runtime version 24.37.0.
[21:58:57 INF] NetDaemon.Runtime.Internal.NetDaemonRuntime: Successfully connected to Home Assistant
[21:58:57 INF] NetDaemon.HassModel.Internal.RegistryCache: Initializing RegistryCache
[21:58:58 INF] NetDaemon.AppModel.Internal.Application: Successfully loaded app InverterAnenji.Anenji4000App
[21:58:58 INF] NetDaemon.AppModel.Internal.AppModelContext: Finished loading applications: Enabled 0, Disabled 0, Running 1, Error 0
[21:59:07 INF] InverterAnenji.Anenji4000App: set>server=192.168.1.200:8899;
[21:59:07 INF] InverterAnenji.Anenji4000App: rsp>server=1;
[21:59:07 INF] InverterAnenji.Anenji4000App: Start listner
[22:00:07 ERR] InverterAnenji.Anenji4000App: AcceptSocketAsync: The operation has timed out.
[22:00:27 INF] InverterAnenji.Anenji4000App: set>server=192.168.1.200:8899;
[22:00:28 INF] InverterAnenji.Anenji4000App: rsp>server=1;
[22:00:28 INF] InverterAnenji.Anenji4000App: Start listner
[22:01:28 ERR] InverterAnenji.Anenji4000App: AcceptSocketAsync: The operation has timed out.
[22:01:48 INF] InverterAnenji.Anenji4000App: set>server=192.168.1.200:8899;
[22:01:48 INF] InverterAnenji.Anenji4000App: rsp>server=1;
[22:01:48 INF] InverterAnenji.Anenji4000App: Start listner
[22:02:48 ERR] InverterAnenji.Anenji4000App: AcceptSocketAsync: The operation has timed out.

So it seems that the listener is not getting any data. I know that the ip address i set in the IPEndPoint WiFiAdapterEndPoint = new IPEndPoint(new IPAddress(new byte[] { 192, 168, 1, 192 }), 58899); is correct, so what could be the issue?

The Wifi dongle is a Wifi Plug Pro 05, just fyi.

UPDATE:
I've noticed that port 8899 was not opened when running the app, and in NetDaemon V4 Configuration tab there's a zone called Network. I had to expose port 10000 as 8899, and now everything is running great! I get all the parameters in MQTT, which is great!

One thing if i may suggest: 
Please implement changing some of the settings via HA, for example:

Register: 301	"Output priority"		{"0": "Utility-PV-Battery","1": "PV-Utility-Battery","2": "PV-Battery-Utility"}
Register: 331	"Battery charging priority"		{"0": "Utility priority;","1": "PV priority;","2": "PV is at the same level as the Utility;","3": "Only PV charging is allowed;"}

Some of these settings could help in creating automations based on certain factors, so they could be very useful.

Thank you again for your work!
