### ISSUE TITLE
No conection to MQTT

### ISSUE THREAD

**Issue by nokia80** [sabatex/NetDaemonApps.InverterAnenji-4kw-7.2kw#4]
Hi @sabatex ,

I use multiple connections for the Mosquitto broker, they work, when I start the netdaemon I don't see in the log of Mosquitto that a connection is established.

I use NetDaemonApps.dll in Daemon to start up, is this correct?

Again the log

  NetDaemon.AppModel.Internal.Application: Error loading app InverterAnenji.Anenji4000App
System.InvalidOperationException: Unable to resolve service for type 'NetDaemon.Extensions.MqttEntityManager.IMqttEntityManager' while attempting to activate 'InverterAnenji.Anenji4000App'.
   at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.ConstructorMatcher.CreateInstance(IServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.CreateInstance(IServiceProvider provider, Type instanceType, Object[] parameters)
   at NetDaemon.AppModel.Internal.AppFactories.FuncAppFactory.<>c__DisplayClass13_0.<CreateFactoryFunc>b__0(IServiceProvider provider)
   at NetDaemon.AppModel.Internal.AppFactories.FuncAppFactory.Create(IServiceProvider provider)
   at NetDaemon.AppModel.Internal.ApplicationContext..ctor(IServiceProvider serviceProvider, IAppFactory appFactory)
   at NetDaemon.AppModel.Internal.Application.InstanceApplication()

Thanks in advance for your help

**Comment by sabatex** [comment]
Do you use Visual Studio Code or Visual Studio?

**Comment by nokia80** [comment]
Visual Studio

**Comment by sabatex** [comment]
Start debug this application in visual studio

**Comment by sabatex** [comment]
correct appsetting.json
"HomeAssistant": {
  "Host": "homeassistant.local",
  "Port": 8123,
  "Ssl": false,
  "Token": "your token"
},
"Mqtt": {
  "Host": "homeassistant.local",
  "UserName": "mqtt",
  "Password": "your password"
}

**Comment by nokia80** [comment]
> homeassistant.local

hi,
i see in your answer that ssl is set to false, when i do that i don't get a connection with home assistant.

ssl is now set to true connects with home assistant but gives the same error see attachment
![Scherm­afbeelding 2024-12-27 om 15 16 10](https://github.com/user-attachments/assets/f694f9e8-4c1b-4b00-86c3-deeb3c462e3d)

**Comment by nokia80** [comment]
Solved thanks
